apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-api-gateway
  template:
    metadata:
      labels:
        app: fleetman-api-gateway
    spec:
      containers:
        - name: fleetman-api-gateway
          image: supinfo4kube/api-gateway:1.0.1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: fleetman-api-gateway
